In [2]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Element in the third row and first column:")
print(arr[2, 0])

print("\nSecond column of the array:")
print(arr[:, 1])

print("\nData type of array elements:")
print(arr.dtype)

print("\nTesting COPY (original should NOT be affected):")
arr_copy = arr.copy()
arr_copy[0, 0] = 999
print(f"Original array first element: {arr[0, 0]}")
print(f"Copy array first element: {arr_copy[0, 0]}")

print("\nTesting VIEW (original SHOULD be affected):")
arr_view = arr.view()
arr_view[0, 0] = 777
print(f"Original array first element: {arr[0, 0]}")
print(f"View array first element: {arr_view[0, 0]}")

arr[0, 0] = 10

print("\nShape of the array:")
print(arr.shape)

print("\nEach element with its position (row, column):")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(f"Position ({i}, {j}): {arr[i, j]}")

print("\nCreating new array and joining:")
new_arr = np.ones_like(arr) * 5
print(f"New array (all 5s):\n{new_arr}")
print(f"\nVertical stack (vstack):\n{np.vstack((arr, new_arr))}")
print(f"\nHorizontal stack (hstack):\n{np.hstack((arr, new_arr))}")

print("\nSplitting array into three column-based arrays:")
split_result = np.hsplit(arr, 3)
for i, part in enumerate(split_result):
    print(f"Part {i+1} (Column {i}):\n{part}")

print("\nSearching for value 60:")
positions = np.where(arr == 60)
print(f"Positions where arr == 60: {positions}")
print(f"Value 60 is at row {positions[0][0]}, column {positions[1][0]}")

print("\nSorting each row in ascending order:")
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)

print("\nFiltering elements greater than 50:")
filtered = arr[arr > 50]
print(filtered)

print("\n2x3 array of random integers (1-100):")
random_arr = np.random.randint(1, 101, size=(2, 3))
print(random_arr)

print("\nApplying NumPy ufuncs:")
print("Square root of each element:")
sqrt_result = np.sqrt(arr)
print(sqrt_result)
print("\nAdding 10 to each element:")
add_result = np.add(arr, 10)
print(add_result)

Element in the third row and first column:
70

Second column of the array:
[20 50 80]

Data type of array elements:
int64

Testing COPY (original should NOT be affected):
Original array first element: 10
Copy array first element: 999

Testing VIEW (original SHOULD be affected):
Original array first element: 777
View array first element: 777

Shape of the array:
(3, 3)

Each element with its position (row, column):
Position (0, 0): 10
Position (0, 1): 20
Position (0, 2): 30
Position (1, 0): 40
Position (1, 1): 50
Position (1, 2): 60
Position (2, 0): 70
Position (2, 1): 80
Position (2, 2): 90

Creating new array and joining:
New array (all 5s):
[[5 5 5]
 [5 5 5]
 [5 5 5]]

Vertical stack (vstack):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [ 5  5  5]
 [ 5  5  5]
 [ 5  5  5]]

Horizontal stack (hstack):
[[10 20 30  5  5  5]
 [40 50 60  5  5  5]
 [70 80 90  5  5  5]]

Splitting array into three column-based arrays:
Part 1 (Column 0):
[[10]
 [40]
 [70]]
Part 2 (Column 1):
[[20]
 [50]
 [80]]
Part 